# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: apex-credentials

steps:

- task: PowerShell@2
  displayName: 'Install SQLcl'
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -OutFile sqlcl.zip
      Expand-Archive sqlcl.zip -DestinationPath sqlcl

- task: DownloadSecureFile@1
  name: walletFile
  inputs:
    secureFile: 'Wallet_atpdb2024.zip'

- task: PowerShell@2
  displayName: 'Extract Wallet'
  inputs:
    targetType: 'inline'
    script: |
      Expand-Archive "$(walletFile.secureFilePath)" -DestinationPath "$(Agent.TempDirectory)\wallet"

- task: CmdLine@2
  displayName: 'Deploy APEX App'
  inputs:
    script: |
      set TNS_ADMIN=$(Agent.TempDirectory)\wallet

      echo Creating deploy script...
      (
        echo whenever sqlerror exit failure
        echo connect $(DB_USER)/"$(DB_PASSWORD)"@atpdb2024_high
        echo begin
        echo   apex_application_install.clear_all;
        echo   apex_application_install.set_workspace(p_workspace =^> '$(TARGET_WORKSPACE)');
        echo   apex_application_install.set_schema(p_schema =^> '$(TARGET_SCHEMA)');
        echo   apex_application_install.set_application_id(p_application_id =^> $(TARGET_APP_ID));
        echo end;
        echo /
        echo @"$(Build.SourcesDirectory)\f114\install.sql"
        echo exit
      ) > deploy_apex.sql

      cd sqlcl\sqlcl\bin

      echo Running deployment...
      sql /nolog @..\..\..\deploy_apex.sql